name: nestjs-graphql-dataloader (publish)

on:
  push:
    branches:
      - develop
    paths:
      - 'package.json'

jobs:
  publish:
    uses: bluescape/reusable-github-workflows/.github/workflows/npm_publish.yml@v1
    with:
      node-version: 16
      packagejson: package.json
      version-check: true
    secrets: inherit